### ISSUE TITLE
Tooltip can't be used within other web components

### ISSUE THREAD

**Issue by caliny97** [eduferfer/kor#15]
Tooltip queries "document" for the target, it won't work when the target is inside a shadow DOM.

**Comment by eduferfer** [comment]
HI Caliny, I am thinking that the best solution could be allowing an HTMLElement to be passed as a target instead of a string, would this solve the issue from your perspective?

**Comment by caliny97** [comment]
Hi Eduardo, passing the target would work, also passing sort of a target retrieval callback will do the work too.
Thanks

**Comment by eduferfer** [comment]
@caliny97 version 1.1.4 has been just released with support for HTMLElement binding.

For more info, please check PR #18 , and if anything does not work as expected please comment again in this issue here.

**Comment by caliny97** [comment]
@eduferfer it works as expected, Thanks for the prompt response.
