### ISSUE TITLE
Using kor-ui

### ISSUE THREAD

**Issue by gcollin** [eduferfer/kor#4]
Just to let you know I've switched to your kor-ui components for one of my project!

The preview component is now running kor-ui, with a nice interface! (But it's just the beginning...)
https://dontcode.github.io/preview-ui
from
https://dontcode.github.io project.

**Comment by eduferfer** [comment]
Nice to hear from you again and great to know you managed to get on board with Kor-UI (though the links do not work for me, but I trust you it is looking nice ^^)

If you come across any bug, limitation or would like a feature to be added, please help me make it grow step by step.
