### ISSUE TITLE
Scrollbars appearing when using select inside a accordion

### ISSUE THREAD

**Issue by gcollin** [eduferfer/kor#7]
Hi all,

I'm using the following code:
```
<kor-accordion label="Add Command" expanded>
  <kor-input label="position" type="select" [value]="position" (value-changed)="position = $event.target.value">
    <kor-menu-item label="creation/name"></kor-menu-item>
    <kor-menu-item label="creation/entities/a/name"></kor-menu-item>
    <kor-menu-item label="creation/screens/a/name"></kor-menu-item>
    <kor-menu-item label="creation/entities/b/name"></kor-menu-item>
    <kor-menu-item label="creation/screens/b/name"></kor-menu-item>
  </kor-input>
  <kor-input label="value" [value]="value" (value-changed)="value = $event.target.value"></kor-input>
  <kor-button slot="footer" label="Add" (click)="addCommand($event)"></kor-button>
</kor-accordion>
```
and when the select is closed, it all looks fine:
![image](https://user-images.githubusercontent.com/771800/85225847-43ca6e00-b3d4-11ea-89bf-eff2e5d595b3.png)

However, if I open the select, it expands beyond the accordion that creates scrollbars.... Not very nice.
![image](https://user-images.githubusercontent.com/771800/85225898-973cbc00-b3d4-11ea-96f0-4c681d3db070.png)

I guess the selection list should be above the rest.

**Comment by eduferfer** [comment]
@gcollin I was able to reproduce and just pushed a fix in release 1.0.10, please take a look and let me know if anything is still not as expected
